{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "219a9e82-489d-4177-9cfa-7e82d168a6be",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q1\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "6903b0f4-0491-4046-97d3-a21fdbd30996",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q2\n",
    "#When an exception is not handled, the program terminates and displays a traceback message, showing the line where the exception occurred and the type of exception.\n",
    "#Example:\n",
    "import logging\n",
    "\n",
    "logging.basicConfig(filename=\"error.log\" ,level=logging.ERROR)\n",
    "\n",
    "try:\n",
    "    result = 10 / 0\n",
    "except ZeroDivisionError as e:\n",
    "    logging.error(\"An exception occurred: %s\", e)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "6c429b56-cba8-4d12-8728-f6fb7bba7088",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q3\n",
    "#The try and except statements are used to catch and handle exceptions in Python.\n",
    "#Example:\n",
    "import logging\n",
    "\n",
    "logging.basicConfig(filename=\"error.log\" , level=logging.ERROR)\n",
    "\n",
    "try:\n",
    "    a = [1, 2, 3]\n",
    "    print(a[3])\n",
    "except IndexError as e:\n",
    "    logging.error(\"An exception occurred: %s\", e)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f3d216df-990d-4ded-afa8-b7e746a0a2b4",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q4\n",
    "#try and else: \n",
    "The else block executes if no exceptions are raised in the try block.\n",
    "#EX:\n",
    "import logging\n",
    "\n",
    "logging.basicConfig(filename=\"error.log\" ,level=logging.INFO)\n",
    "\n",
    "try:\n",
    "    num = 10 / 2\n",
    "except ZeroDivisionError as e:\n",
    "    logging.error(\"An exception occurred: %s\", e)\n",
    "else:\n",
    "    logging.info(\"No exceptions occurred. The result is %d\", num)\n",
    "\n",
    "\n",
    "    \n",
    "#finally: \n",
    "    The finally block executes regardless of whether an exception is raised or not.\n",
    "#Ex:\n",
    "import logging\n",
    "\n",
    "logging.basicConfig(filename=\"error.log\" ,level=logging.INFO)\n",
    "\n",
    "try:\n",
    "    num = 10 / 0\n",
    "except ZeroDivisionError as e:\n",
    "    logging.error(\"An exception occurred: %s\", e)\n",
    "finally:\n",
    "    logging.info(\"This block is executed no matter what.\")\n",
    "\n",
    "\n",
    "#raise:\n",
    "The raise statement is used to manually raise an exception.\n",
    "\n",
    "#Ex:\n",
    "import logging\n",
    "\n",
    "logging.basicConfig(filename=\"error.log\" , level=logging.ERROR)\n",
    "\n",
    "def check_value(x):\n",
    "    if x < 0:\n",
    "        raise ValueError(\"Negative values are not allowed\")\n",
    "    return x\n",
    "\n",
    "try:\n",
    "    value = check_value(-1)\n",
    "except ValueError as e:\n",
    "    logging.error(\"An exception occurred: %s\", e)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "feca4611-d6ee-440e-abbb-5c34d82325ac",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q5\n",
    "Custom exceptions are user-defined exceptions that extend Python's built-in Exception class. They allow for more specific error handling and can provide more descriptive error messages.\n",
    "\n",
    "#Why we need Custom Exceptions:\n",
    "\n",
    "To give more specific error messages.\n",
    "\n",
    "To handle specific error situations more effectively.\n",
    "\n",
    "To make the code easier to understand and maintain.\n",
    "\n",
    "#ex:\n",
    "    import logging\n",
    "\n",
    "logging.basicConfig(filename=\"error.log\" , level=logging.ERROR)\n",
    "\n",
    "class NegativeNumberError(Exception):\n",
    "    pass\n",
    "\n",
    "def check_positive(number):\n",
    "    if number < 0:\n",
    "        raise NegativeNumberError(\"Negative numbers are not allowed\")\n",
    "    return number\n",
    "\n",
    "try:\n",
    "    check_positive(-5)\n",
    "except NegativeNumberError as e:\n",
    "    logging.error(\"An error occurred: %s\", e)\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
